'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { request } from '@/lib/community/shared'
import './community.css'
export default function AdminCommunity(){
 const [kind,setKind]=useState('reports'),[page,setPage]=useState(1),[items,setItems]=useState<any[]>([]),[people,setPeople]=useState<any[]>([]),[total,setTotal]=useState(0),[status,setStatus]=useState(''),[tick,setTick]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true;setLoading(true);setError('');request(`/api/admin/community?kind=${kind}&page=${page}&status=${status}`).then(d=>{if(active){setItems(d.items);setPeople(d.people);setTotal(d.total)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[kind,page,status,tick])
 async function moderate(targetKind:string,id:string,next:string){if(busy)return;if(['removed','suspended'].includes(next)&&!confirm(next==='suspended'?'Suspender este usuário?':'Remover este conteúdo da Comunidade?'))return;setBusy(true);setError('');try{await request('/api/admin/community',{kind:targetKind,id,status:next},'PATCH');setTick(t=>t+1)}catch(e){setError(e instanceof Error?e.message:'Falha na moderação.')}finally{setBusy(false)}}
 const name=(id:string)=>people.find(p=>p.id===id)?.name||'Usuário indisponível'
 return <section className="cm-root cm-admin"><div className="cm-card"><h2>Moderação da Comunidade</h2><p>Denúncias aguardam análise humana. Ocultar e remover retiram o conteúdo do feed; os registros permanecem disponíveis para revisão.</p><div className="cm-filters">{[['reports','Denúncias e usuários'],['posts','Publicações'],['comments','Comentários']].map(([k,label])=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setPage(1);setStatus('')}}>{label}</button>)}</div><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos</option>{(kind==='reports'?[['open','Aberta'],['reviewed','Analisada'],['dismissed','Arquivada']]:[['published','Publicado'],['hidden','Oculto'],['removed','Removido']]).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button onClick={()=>setTick(t=>t+1)}>Atualizar</button></div>
 {error&&<p className="cm-error" role="alert">{error}</p>}{loading?<p role="status">Carregando…</p>:<>{!items.length&&<div className="cm-card">Nenhum registro encontrado.</div>}{items.map(item=><article key={item.id} className="cm-card"><div className="cm-row"><strong>{kind==='reports'?item.reason:name(item.user_id)}</strong><small>{item.status} · {new Date(item.created_at).toLocaleString('pt-BR')}</small></div><p className="cm-content">{item.content||item.snapshot}</p>{item.details&&<p>{item.details}</p>}{kind==='posts'&&<div className="cm-previews">{(item.media||[]).map((m:any)=>m.url?<div key={m.path}>{m.type.startsWith('video/')?<video controls src={m.url} preload="none"/>:<img src={m.url} alt="Mídia da publicação" loading="lazy"/>}</div>:null)}</div>}
 <div className="cm-row">{(kind==='posts'||item.post_id)&&<Link href={`/comunidade/post/${kind==='posts'?item.id:item.post_id}`}>Abrir publicação ↗</Link>}{kind==='reports'?<><button disabled={busy} onClick={()=>moderate(kind,item.id,'reviewed')}>Marcar analisada</button><button disabled={busy} onClick={()=>moderate(kind,item.id,'dismissed')}>Arquivar denúncia</button>{item.post_id&&<button disabled={busy} onClick={()=>moderate(item.comment_id?'comments':'posts',item.comment_id||item.post_id,'hidden')}>Ocultar conteúdo denunciado</button>}</>:<><button disabled={busy} onClick={()=>moderate(kind,item.id,'hidden')}>Ocultar</button><button disabled={busy} onClick={()=>moderate(kind,item.id,'published')}>Restaurar</button><button disabled={busy} onClick={()=>moderate(kind,item.id,'removed')}>Remover</button></>}</div>
 {kind==='reports'&&item.reported_user_id&&<div className="cm-report"><Link href={`/comunidade/usuario/${item.reported_user_id}`}>Usuário denunciado: {name(item.reported_user_id)}</Link><p>Enviada por: {name(item.reported_by)}</p><p>Status da conta: {people.find(p=>p.id===item.reported_user_id)?.account_status}</p><div className="cm-row"><button disabled={busy} onClick={()=>moderate('user',item.reported_user_id,'suspended')}>Suspender usuário</button><button disabled={busy} onClick={()=>moderate('user',item.reported_user_id,'active')}>Reativar usuário</button></div></div>}
 </article>)}</>}
 <div className="cm-row"><button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} · {total} registros</span><button disabled={page*20>=total||loading} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></section>
}
