'use client'
import { useState } from 'react'
import './post-social.css'
import Link from 'next/link'
import { Heart,MessageCircle,Bookmark,Share2,MoreHorizontal,Flag,Car } from 'lucide-react'
import { request,REASONS,safeImage,type CommunityPost } from '@/lib/community/shared'
import FollowUserButton from '@/components/FollowUserButton'
import EventAttendance from '@/components/events/EventAttendance'
import Composer from './Composer'
import VerifiedAvatarBadge from '@/components/VerifiedAvatarBadge'
export default function PostCard({post:p,viewer,isAdmin,onChange}:{post:CommunityPost;viewer:string|null;isAdmin:boolean;onChange:()=>void}){
 const [liked,setLiked]=useState(p.liked),[saved,setSaved]=useState(p.saved),[likes,setLikes]=useState(Number(p.likes_count)),[count,setCount]=useState(Number(p.comments_count))
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[comments,setComments]=useState<any[]|null>(null),[page,setPage]=useState(1),[more,setMore]=useState(false)
 const [text,setText]=useState(''),[commentId,setCommentId]=useState(()=>crypto.randomUUID()),[report,setReport]=useState<string|null|false>(false),[reason,setReason]=useState<string>(REASONS[0]),[details,setDetails]=useState(''),[notice,setNotice]=useState('')
 const [expanded,setExpanded]=useState(false)
 const preview=p.content.split('\n').slice(0,3).join('\n').slice(0,180)
 const truncated=preview.length<p.content.length
 const caption=expanded?p.content:preview
 const url=()=>`${window.location.origin}/comunidade/post/${p.id}`
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setBusy(false)}}
 async function loadComments(next=1){const d=await request(`/api/community?mode=comments&post=${p.id}&page=${next}`);setComments(c=>next===1?d.items:[...(c||[]),...d.items]);setPage(next);setMore(d.hasMore)}
 async function copy(){await navigator.clipboard.writeText(url());setNotice('Link copiado.')}
 if(editing)return <Composer initial={p} onClose={()=>setEditing(false)} onDone={()=>{setEditing(false);onChange()}}/>
 return <article className="cm-card cm-post">
  <header className="cm-post-head"><Link className="cm-author" href={`/comunidade/usuario/${p.user_id}`}><span className="verified-avatar-wrap"><span className="cm-avatar">{safeImage(p.author?.avatar_url)?<img src={safeImage(p.author.avatar_url)} alt="" loading="lazy"/>:(p.author?.name||'F').slice(0,1)}</span><VerifiedAvatarBadge active={p.author?.is_verified}/></span><span><strong>{p.author?.name||'Membro FULLSEND'}</strong><small><time dateTime={p.created_at}>{new Date(p.created_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</time>{p.city?` · ${p.city}${p.state?` / ${p.state}`:''}`:''}</small></span></Link>
  <details className="cm-menu"><summary aria-label="Opções da publicação"><MoreHorizontal size={22}/></summary><div><button onClick={()=>act(copy)}>Copiar link</button><button onClick={()=>setReport(null)}>Denunciar</button>{viewer===p.user_id&&<><button onClick={()=>setEditing(true)}>Editar publicação</button><button disabled={busy} onClick={()=>{if(confirm('Excluir esta publicação?'))act(async()=>{await request('/api/community',{action:'post',id:p.id},'DELETE');onChange()})}}>Excluir publicação</button></>}{isAdmin&&<button disabled={busy} onClick={()=>act(async()=>{await request('/api/admin/community',{kind:'posts',id:p.id,status:'hidden'},'PATCH');onChange()})}>Ocultar como administrador</button>}</div></details></header>
  {!!p.media.length&&<div tabIndex={p.media.length>1?0:undefined} aria-label="Fotos e vídeos da publicação" className={`cm-media ${p.media.length>1?'cm-media-multiple':''}`}>{p.media.map((m,i)=><div key={m.path}>{m.url?(m.type.startsWith('video/')?<video src={m.url} controls playsInline preload="none" aria-label={`Vídeo ${i+1} da publicação`}/>:<img src={m.url} alt={`${p.title||'Publicação de '+p.author?.name} — foto ${i+1}`} loading="lazy"/>):<p>Mídia indisponível. Atualize a página.</p>}</div>)}</div>}
  {p.media.length>1&&<p className="cm-gallery-hint">{p.media.length} fotos/vídeos · Deslize para ver mais →</p>}
  <div className="cm-actions"><button aria-pressed={liked} disabled={busy} onClick={()=>act(async()=>{const result=await request('/api/community',{action:'like',id:p.id,enabled:!liked});setLikes(Number(result.count));setLiked(result.enabled)})}><Heart size={24} fill={liked?'currentColor':'none'}/><span>{likes} {liked?'Curtido':'Curtir'}</span></button><button disabled={busy} onClick={()=>act(async()=>{if(comments)setComments(null);else await loadComments()})}><MessageCircle size={24}/><span>{count} Comentar</span></button><button disabled={busy} onClick={()=>act(async()=>{if(navigator.share){try{await navigator.share({title:'FULLSEND Comunidade',url:url()})}catch(e){if((e as Error).name!=='AbortError')await copy()}}else await copy()})}><Share2 size={24}/><span>Compartilhar</span></button><button aria-pressed={saved} disabled={busy} onClick={()=>act(async()=>{await request('/api/community',{action:'save',id:p.id,enabled:!saved});setSaved(!saved)})}><Bookmark size={24} fill={saved?'currentColor':'none'}/><span>{saved?'Salvo':'Salvar'}</span></button></div>
  <div className="cm-row cm-meta"><span>{p.post_type} · {p.category}</span>{viewer!==p.user_id&&<FollowUserButton userId={p.user_id} compact/>}</div>
  {p.vehicle&&<Link className="cm-vehicle" href={`/comunidade/projeto/${p.vehicle.id}`}><Car size={17}/>{p.vehicle.title}<span>Ver projeto →</span></Link>}
  {p.project_date&&<div className="cm-diary-tag">DIÁRIO DO PROJETO · {p.project_date.split('-').reverse().join('/')}</div>}
  {p.title&&<h2>{p.title}</h2>}<p className="cm-content">{caption.split(/(#[\p{L}\p{N}_]+)/gu).map((part,i)=>part.startsWith('#')?<Link key={i} href={`/comunidade/tag/${encodeURIComponent(part.slice(1).toLowerCase())}`}>{part}</Link>:part)}{truncated&&!expanded?'…':''}</p>{truncated&&<button type="button" className="cm-caption-toggle" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'menos':'mais'}</button>}
  {p.parts&&<p className="cm-content"><b>Peças instaladas:</b> {p.parts}</p>}
  {(p.power!==null||p.cost!==null)&&<div className="cm-specs">{p.power!==null&&<span>{Number(p.power).toLocaleString('pt-BR')} cv</span>}{p.cost!==null&&<span>Custo: {Number(p.cost).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</span>}</div>}

  <div className="cm-tags">{p.tags.map(t=><Link key={t} href={`/comunidade/tag/${encodeURIComponent(t)}`}>#{t}</Link>)}</div>
  {p.event&&<div className="cm-event"><Link href={`/eventos/${p.event.slug}`}><b>{p.event.title}</b><small>{p.event.event_date?.split('-').reverse().join('/')} {p.event.event_time?.slice(0,5)} · {p.event.venue} · {p.event.city} / {p.event.state}</small></Link>{p.event.status==='published'?<EventAttendance eventId={p.event.id}/>:<small>Aguardando aprovação na agenda</small>}</div>}

  <div className="cm-share"><Link href={`/comunidade/post/${p.id}`}>Abrir publicação</Link><button onClick={()=>window.open(`https://wa.me/?text=${encodeURIComponent(url())}`,'_blank','noopener,noreferrer')}>WhatsApp ↗</button><button onClick={()=>act(copy)}>Copiar link</button></div>
  {comments&&<section className="cm-comments" aria-label="Comentários">{comments.length===0&&<p className="cm-muted">Seja o primeiro a comentar.</p>}{comments.map(c=><div key={c.id} className="cm-comment"><Link href={`/comunidade/usuario/${c.user_id}`} className="cm-author"><span className="verified-avatar-wrap"><span className="cm-avatar cm-avatar-small">{safeImage(c.author?.avatar_url)?<img src={safeImage(c.author.avatar_url)} alt="" loading="lazy"/>:(c.author?.name||'F').slice(0,1)}</span><VerifiedAvatarBadge active={c.author?.is_verified}/></span><b>{c.author?.name||'Membro FULLSEND'}</b></Link><p>{c.content}</p><small>{new Date(c.created_at).toLocaleString('pt-BR')}</small><div className="cm-row">{viewer===c.user_id&&<button disabled={busy} onClick={()=>act(async()=>{await request('/api/community',{action:'comment',id:c.id},'DELETE');setCount(n=>Math.max(0,n-1));await loadComments()})}>Excluir</button>}{isAdmin&&<button disabled={busy} onClick={()=>act(async()=>{await request('/api/admin/community',{kind:'comments',id:c.id,status:'hidden'},'PATCH');setCount(n=>Math.max(0,n-1));await loadComments()})}>Ocultar</button>}<button onClick={()=>setReport(c.id)}>Denunciar</button></div></div>)}{more&&<button disabled={busy} onClick={()=>act(()=>loadComments(page+1))}>Mais comentários</button>}<form onSubmit={e=>{e.preventDefault();act(async()=>{await request('/api/community',{action:'comment',id:p.id,commentId,content:text});setText('');setCommentId(crypto.randomUUID());setCount(n=>n+1);await loadComments()})}}><label>Seu comentário<textarea required maxLength={1500} value={text} onChange={e=>setText(e.target.value)} rows={2}/></label><button className="cm-primary" disabled={busy}>Comentar</button></form></section>}
  {report!==false&&<form className="cm-report" onSubmit={e=>{e.preventDefault();act(async()=>{await request('/api/community',{action:'report',id:p.id,commentId:report,reason,details});setReport(false);setNotice('Denúncia enviada para análise administrativa.')})}}><h3><Flag size={16}/> Denunciar conteúdo</h3><label>Motivo<select value={reason} onChange={e=>setReason(e.target.value)}>{REASONS.map(r=><option key={r}>{r}</option>)}</select></label><label>Detalhes (opcional)<textarea maxLength={1000} value={details} onChange={e=>setDetails(e.target.value)}/></label><div className="cm-row"><button type="button" onClick={()=>setReport(false)}>Cancelar</button><button disabled={busy} className="cm-primary">Enviar denúncia</button></div></form>}
  {error&&<p role="alert" className="cm-error">{error}</p>}{notice&&<p role="status" className="cm-notice">{notice}</p>}
 </article>
}
