'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronLeft, Film, Music2, Pause, Play, Scissors, Trash2, Upload, Volume2, X, Zap } from 'lucide-react'
import './video-studio.css'

type MusicTrack={id:string;file:File;url:string;start:number;volume:number;duration:number}
type Ratio='original'|'vertical'|'square'

const fmt=(value:number)=>{const safe=Math.max(0,Number.isFinite(value)?value:0);const minutes=Math.floor(safe/60);return `${minutes}:${Math.floor(safe%60).toString().padStart(2,'0')}.${Math.floor((safe%1)*10)}`}
const wait=(media:HTMLMediaElement,event:string)=>new Promise<void>((resolve,reject)=>{const done=()=>{cleanup();resolve()};const fail=()=>{cleanup();reject(new Error('Não foi possível ler esta mídia.'))};const cleanup=()=>{media.removeEventListener(event,done);media.removeEventListener('error',fail)};media.addEventListener(event,done,{once:true});media.addEventListener('error',fail,{once:true})})

export default function VideoStudio({file,onCancel,onConfirm}:{file:File;onCancel:()=>void;onConfirm:(file:File)=>void}){
 const sourceUrl=useMemo(()=>URL.createObjectURL(file),[file])
 const videoRef=useRef<HTMLVideoElement>(null),musicInput=useRef<HTMLInputElement>(null),audioRefs=useRef(new Map<string,HTMLAudioElement>())
 const [duration,setDuration]=useState(0),[current,setCurrent]=useState(0),[start,setStart]=useState(0),[end,setEnd]=useState(0)
 const [playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[ratio,setRatio]=useState<Ratio>('original')
 const [tracks,setTracks]=useState<MusicTrack[]>([]),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('')
 useEffect(()=>()=>{URL.revokeObjectURL(sourceUrl);tracks.forEach(t=>URL.revokeObjectURL(t.url))},[sourceUrl])
 useEffect(()=>{const v=videoRef.current;if(v)v.playbackRate=speed;audioRefs.current.forEach(a=>a.playbackRate=speed)},[speed])
 function syncMusic(time:number,shouldPlay=playing){tracks.forEach(track=>{const audio=audioRefs.current.get(track.id);if(!audio)return;const local=time-track.start;audio.volume=track.volume;audio.playbackRate=speed;if(local>=0&&local<track.duration){if(Math.abs(audio.currentTime-local)>0.45)audio.currentTime=local;if(shouldPlay)audio.play().catch(()=>{})}else{audio.pause();audio.currentTime=0}})}
 function seek(value:number){const next=Math.min(end||duration,Math.max(start,value));setCurrent(next);if(videoRef.current)videoRef.current.currentTime=next;syncMusic(next,false)}
 async function toggle(){const v=videoRef.current;if(!v)return;if(v.paused){if(v.currentTime<start||v.currentTime>=end)v.currentTime=start;setPlaying(true);syncMusic(v.currentTime,true);await v.play().catch(()=>setError('Toque novamente para iniciar a prévia.'))}else{v.pause()}}
 function addMusic(files:FileList|null){const picked=Array.from(files||[]);if(!picked.length)return;if(tracks.length+picked.length>4){setError('A timeline aceita 1 vídeo e até 4 faixas de música.');return}setError('');for(const pickedFile of picked){if(!pickedFile.type.startsWith('audio/')){setError('Escolha um arquivo de áudio válido.');continue}const url=URL.createObjectURL(pickedFile),audio=new Audio(url);audio.preload='metadata';audio.onloadedmetadata=()=>setTracks(items=>[...items,{id:crypto.randomUUID(),file:pickedFile,url,start,volume:.85,duration:Number.isFinite(audio.duration)?audio.duration:0}]);audio.onerror=()=>{URL.revokeObjectURL(url);setError(`Não foi possível abrir ${pickedFile.name}.`)}}}
 function removeTrack(id:string){setTracks(items=>{const found=items.find(t=>t.id===id);if(found)URL.revokeObjectURL(found.url);return items.filter(t=>t.id!==id)})}
 function updateTrack(id:string,patch:Partial<MusicTrack>){setTracks(items=>items.map(t=>t.id===id?{...t,...patch}:t))}
 function dimensions(video:HTMLVideoElement){if(ratio==='vertical')return {width:720,height:1280};if(ratio==='square')return {width:900,height:900};const scale=Math.min(1,1280/Math.max(video.videoWidth,video.videoHeight));return {width:Math.max(2,Math.round(video.videoWidth*scale/2)*2),height:Math.max(2,Math.round(video.videoHeight*scale/2)*2)}}
 function drawCover(ctx:CanvasRenderingContext2D,video:HTMLVideoElement,width:number,height:number){const sourceRatio=video.videoWidth/video.videoHeight,targetRatio=width/height;let sx=0,sy=0,sw=video.videoWidth,sh=video.videoHeight;if(sourceRatio>targetRatio){sw=video.videoHeight*targetRatio;sx=(video.videoWidth-sw)/2}else{sh=video.videoWidth/targetRatio;sy=(video.videoHeight-sh)/2}ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);ctx.drawImage(video,sx,sy,sw,sh,0,0,width,height)}
 async function exportVideo(){if(exporting||!duration)return;setExporting(true);setError('');setProgress(0);let context:AudioContext|null=null;try{
  if(typeof MediaRecorder==='undefined')throw new Error('Este navegador não oferece o processamento de vídeo necessário. Atualize o Chrome ou Edge.')
  const renderVideo=document.createElement('video');renderVideo.src=sourceUrl;renderVideo.preload='auto';renderVideo.playsInline=true;if(renderVideo.readyState<1)await wait(renderVideo,'loadedmetadata')
  const canvas=document.createElement('canvas'),size=dimensions(renderVideo);canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Não foi possível iniciar o processador de vídeo.')
  const canvasStream=canvas.captureStream(30);context=new AudioContext();const destination=context.createMediaStreamDestination();const mainSource=context.createMediaElementSource(renderVideo);const mainGain=context.createGain();mainGain.gain.value=1;mainSource.connect(mainGain).connect(destination)
  const renderTracks=tracks.map(track=>{const audio=new Audio(track.url);audio.preload='auto';audio.crossOrigin='anonymous';audio.playbackRate=speed;const source=context!.createMediaElementSource(audio),gain=context!.createGain();gain.gain.value=track.volume;source.connect(gain).connect(destination);return {track,audio,started:false}})
  const stream=new MediaStream([...canvasStream.getVideoTracks(),...destination.stream.getAudioTracks()]);const options=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(type=>MediaRecorder.isTypeSupported(type));const recorder=new MediaRecorder(stream,options?{mimeType:options,videoBitsPerSecond:2_200_000,audioBitsPerSecond:128_000}:undefined);const chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)}
  const complete=new Promise<File>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('O navegador interrompeu o processamento.'));recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});if(!blob.size)return reject(new Error('O vídeo processado ficou vazio.'));resolve(new File([blob],`${file.name.replace(/\.[^.]+$/,'')}-fullsend.webm`,{type:'video/webm',lastModified:Date.now()}))}})
  renderVideo.currentTime=start;await wait(renderVideo,'seeked').catch(()=>{});renderVideo.playbackRate=speed;await context.resume();recorder.start(1000);await renderVideo.play()
  const startedAt=performance.now();await new Promise<void>((resolve,reject)=>{let frame=0;const paint=()=>{try{drawCover(ctx,renderVideo,canvas.width,canvas.height);const t=renderVideo.currentTime;setProgress(Math.min(99,Math.max(0,((t-start)/Math.max(.1,end-start))*100)));renderTracks.forEach(item=>{const local=t-item.track.start;if(local>=0&&local<item.track.duration){if(!item.started){item.started=true;item.audio.currentTime=Math.max(0,local);item.audio.play().catch(()=>{})}}else if(item.started){item.audio.pause();item.started=false}});if(t>=end-.025||renderVideo.ended||performance.now()-startedAt>Math.max(30_000,((end-start)/speed+15)*1000)){resolve();return}frame=requestAnimationFrame(paint)}catch(cause){reject(cause)}};frame=requestAnimationFrame(paint);renderVideo.addEventListener('error',()=>{cancelAnimationFrame(frame);reject(new Error('O arquivo de vídeo apresentou erro durante a leitura.'))},{once:true})})
  renderVideo.pause();renderTracks.forEach(item=>item.audio.pause());recorder.stop();const output=await complete;setProgress(100);onConfirm(output)
 }catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível processar este vídeo. Você ainda pode usar o arquivo original.')}finally{await context?.close().catch(()=>{});setExporting(false)}}
 return <div className="fs-studio-backdrop" role="dialog" aria-modal="true" aria-label="Editor de vídeo FULLSEND Studio">
  <section className="fs-studio">
   <header className="fs-studio-head"><div><span>FULLSEND STUDIO</span><h2><Zap size={22}/> CORTE DE ALTA PERFORMANCE</h2><p>Prepare o vídeo, misture músicas e publique direto na comunidade.</p></div><button type="button" onClick={onCancel} disabled={exporting} aria-label="Fechar"><X/></button></header>
   <main className="fs-studio-workspace">
    <aside className="fs-studio-tools"><h3><Film size={16}/> FORMATO</h3>{([['original','Original'],['vertical','Reels 9:16'],['square','Quadrado 1:1']] as [Ratio,string][]).map(([value,label])=><button key={value} className={ratio===value?'active':''} onClick={()=>setRatio(value)}>{label}</button>)}<h3><Zap size={16}/> VELOCIDADE</h3><div className="fs-speed-grid">{[.5,1,1.5,2].map(value=><button key={value} className={speed===value?'active':''} onClick={()=>setSpeed(value)}>{value}x</button>)}</div><div className="fs-source-info"><b>{file.name}</b><small>{(file.size/1024/1024).toFixed(1)} MB · saída otimizada em WebM</small></div></aside>
    <div className="fs-studio-preview"><div className={`fs-video-frame ratio-${ratio}`}><video ref={videoRef} src={sourceUrl} playsInline preload="metadata" onLoadedMetadata={e=>{const value=e.currentTarget.duration||0;setDuration(value);setEnd(value);setCurrent(0)}} onTimeUpdate={e=>{const time=e.currentTarget.currentTime;setCurrent(time);syncMusic(time,true);if(end&&time>=end){e.currentTarget.pause();seek(start)}}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);audioRefs.current.forEach(a=>a.pause())}}/></div><div className="fs-preview-controls"><button onClick={toggle} aria-label={playing?'Pausar':'Reproduzir'}>{playing?<Pause/>:<Play/>}</button><span>{fmt(current)} / {fmt(duration)}</span><input type="range" min={start} max={end||1} step="0.05" value={Math.min(current,end||0)} onChange={e=>seek(Number(e.target.value))}/></div></div>
    <aside className="fs-studio-music"><h3><Music2 size={17}/> MÚSICA</h3><p>Adicione até quatro músicas. O áudio será incorporado ao vídeo final.</p><input ref={musicInput} hidden type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg" multiple onChange={e=>{addMusic(e.target.files);e.target.value=''}}/><button className="fs-add-music" onClick={()=>musicInput.current?.click()} disabled={tracks.length>=4||exporting}><Upload size={16}/> ADICIONAR MÚSICA</button><strong>{tracks.length}/4 faixas de áudio</strong></aside>
   </main>
   <section className="fs-timeline"><div className="fs-timeline-title"><div><Scissors size={18}/><span>TIMELINE</span><small>Arraste os controles para cortar</small></div><b>{fmt(Math.max(0,end-start))}</b></div>
    <div className="fs-trim-controls"><label>INÍCIO <input type="range" min="0" max={Math.max(0,end-.1)} step="0.1" value={start} onChange={e=>{const value=Number(e.target.value);setStart(value);seek(value)}}/><b>{fmt(start)}</b></label><label>FIM <input type="range" min={Math.min(duration,start+.1)} max={duration||1} step="0.1" value={end} onChange={e=>setEnd(Number(e.target.value))}/><b>{fmt(end)}</b></label></div>
    <div className="fs-tracks"><div className="fs-track"><div className="fs-track-label"><Film size={15}/><span>VÍDEO</span></div><div className="fs-track-lane"><div className="fs-video-clip" style={{left:`${duration?start/duration*100:0}%`,width:`${duration?(end-start)/duration*100:100}%`}}><span>{file.name}</span><i/></div><div className="fs-playhead" style={{left:`${duration?current/duration*100:0}%`}}/></div></div>{tracks.map((track,index)=><div className="fs-track" key={track.id}><div className="fs-track-label"><Music2 size={15}/><span>ÁUDIO {index+1}</span></div><div className="fs-track-lane"><audio ref={node=>{if(node)audioRefs.current.set(track.id,node);else audioRefs.current.delete(track.id)}} src={track.url} preload="metadata"/><div className="fs-audio-clip" style={{left:`${duration?track.start/duration*100:0}%`,width:`${duration?Math.min(track.duration,duration-track.start)/duration*100:20}%`}}><span>{track.file.name}</span></div></div><div className="fs-track-actions"><label title="Início da música">↦ <input type="number" min="0" max={duration} step="0.1" value={track.start} onChange={e=>updateTrack(track.id,{start:Math.max(0,Math.min(duration,Number(e.target.value)))})}/></label><label title="Volume"><Volume2 size={13}/><input type="range" min="0" max="1" step="0.05" value={track.volume} onChange={e=>updateTrack(track.id,{volume:Number(e.target.value)})}/></label><button onClick={()=>removeTrack(track.id)} aria-label={`Remover ${track.file.name}`}><Trash2 size={14}/></button></div></div>)}</div>
   </section>
   {error&&<div className="fs-studio-error" role="alert">{error}</div>}{exporting&&<div className="fs-render-progress" role="status"><div style={{width:`${progress}%`}}/><span>PROCESSANDO {Math.round(progress)}% · mantenha esta janela aberta</span></div>}
   <footer className="fs-studio-footer"><button onClick={onCancel} disabled={exporting}><ChevronLeft size={17}/> CANCELAR</button><div><button className="fs-use-original" onClick={()=>onConfirm(file)} disabled={exporting}>USAR ORIGINAL</button><button className="fs-render" onClick={exportVideo} disabled={exporting||!duration||end-start<.2}><Check size={18}/>{exporting?'PROCESSANDO…':'CONFIRMAR EDIÇÃO'}</button></div></footer>
  </section>
 </div>
}
