'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronLeft, Image as ImageIcon, Pause, Play, RotateCcw, Save, Scissors, Sparkles, Trash2, Volume2, X } from 'lucide-react'
import './video-studio.css'

type Ratio='vertical'|'square'|'wide'|'original'
type Quality='1080'|'720'|'auto'
type Segment={id:string;start:number;end:number;keep:boolean}
type MusicTrack={id:string;file:File;url:string;start:number;volume:number;duration:number}
type Caption={id:string;start:number;end:number;text:string}
type Tool='cut'|'music'|'captions'|'format'|'speed'|'text'|'cover'

const uid=()=>crypto.randomUUID()
const fmt=(value:number)=>{const safe=Math.max(0,Number.isFinite(value)?value:0),h=Math.floor(safe/3600),m=Math.floor((safe%3600)/60),s=Math.floor(safe%60),d=Math.floor((safe%1)*10);return h?`${h}:${m.toString().padStart(2,'0')}:${s.toString().padStart(2,'0')}`:`${m.toString().padStart(2,'0')}:${s.toString().padStart(2,'0')}.${d}`}
const wait=(media:HTMLMediaElement,event:string)=>new Promise<void>((resolve,reject)=>{const done=()=>{clean();resolve()},fail=()=>{clean();reject(new Error('Não foi possível ler esta mídia.'))},clean=()=>{media.removeEventListener(event,done);media.removeEventListener('error',fail)};media.addEventListener(event,done,{once:true});media.addEventListener('error',fail,{once:true})})
function recorderType(){if(typeof MediaRecorder==='undefined')return '';return ['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(type=>MediaRecorder.isTypeSupported(type))||''}

export default function VideoStudio({file,onCancel,onConfirm}:{file:File;onCancel:()=>void;onConfirm:(file:File)=>void}){
 const sourceUrl=useMemo(()=>URL.createObjectURL(file),[file])
 const videoRef=useRef<HTMLVideoElement>(null),stageRef=useRef<HTMLDivElement>(null),musicInput=useRef<HTMLInputElement>(null),tracksRef=useRef<MusicTrack[]>([])
 const [duration,setDuration]=useState(0),[current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[muted,setMuted]=useState(false),[fullscreen,setFullscreen]=useState(false)
 const [ratio,setRatio]=useState<Ratio>('vertical'),[quality,setQuality]=useState<Quality>('1080'),[speed,setSpeed]=useState<.5|1|1.5|2>(1),[volume,setVolume]=useState(.76),[tool,setTool]=useState<Tool>('cut')
 const [segments,setSegments]=useState<Segment[]>([]),[activeSegment,setActiveSegment]=useState(0),[undoStack,setUndoStack]=useState<Segment[][]>([])
 const [tracks,setTracks]=useState<MusicTrack[]>([]),[captions,setCaptions]=useState<Caption[]>([]),[overlayText,setOverlayText]=useState(''),[coverTime,setCoverTime]=useState(0)
 const [captionStatus,setCaptionStatus]=useState<'idle'|'working'|'ready'|'error'>('idle'),[captionMessage,setCaptionMessage]=useState('Toque para gerar legendas automáticas no navegador.')
 const [detecting,setDetecting]=useState(false),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('')
 const active=segments[activeSegment]
 useEffect(()=>{tracksRef.current=tracks},[tracks])
 useEffect(()=>()=>{URL.revokeObjectURL(sourceUrl);tracksRef.current.forEach(t=>URL.revokeObjectURL(t.url))},[sourceUrl])
 useEffect(()=>{const v=videoRef.current;if(v){v.playbackRate=speed;v.volume=volume;v.muted=muted}},[speed,volume,muted])
 useEffect(()=>{const sync=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync)},[])

 function snapshot(){setUndoStack(stack=>[...stack.slice(-9),segments.map(s=>({...s}))])}
 function undo(){const prev=undoStack.at(-1);if(!prev)return;setSegments(prev);setUndoStack(stack=>stack.slice(0,-1));setActiveSegment(Math.min(activeSegment,Math.max(0,prev.length-1)))}
 function seek(value:number){const next=Math.max(0,Math.min(duration||0,value));setCurrent(next);const v=videoRef.current;if(v&&Math.abs(v.currentTime-next)>.04)v.currentTime=next}
 async function toggle(){const v=videoRef.current;if(!v)return;if(v.paused){v.playbackRate=speed;v.volume=volume;v.muted=muted;await v.play().catch(()=>setError('O navegador bloqueou a reprodução. Toque novamente.'))}else v.pause()}
 function jump(seconds:number){seek(current+seconds)}
 function stepFrame(direction:-1|1){videoRef.current?.pause();seek(current+direction/30)}
 function cycleSpeed(){const values=[.5,1,1.5,2] as const;const next=values[(values.indexOf(speed)+1)%values.length];setSpeed(next)}
 async function toggleFullscreen(){const stage=stageRef.current;if(!stage)return;try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen()}catch{setError('Tela cheia não está disponível neste navegador.')}}
 function selectSegment(index:number){setActiveSegment(index);const seg=segments[index];if(seg)seek(seg.start)}
 function patchActive(patch:Partial<Segment>){if(!active)return;snapshot();setSegments(items=>items.map((s,i)=>i===activeSegment?{...s,...patch}:s))}
 function splitHere(){if(!active||current<=active.start+.15||current>=active.end-.15)return;snapshot();setSegments(items=>{const next=[...items];next.splice(activeSegment,1,{...active,id:uid(),end:current},{...active,id:uid(),start:current});return next});setActiveSegment(activeSegment+1)}
 function setKeep(index:number,keep:boolean){const target=segments[index];if(!target||target.keep===keep)return;snapshot();setSegments(items=>items.map((s,i)=>i===index?{...s,keep}:s))}
 function toggleKeep(index:number){const target=segments[index];if(target)setKeep(index,!target.keep)}
 function deleteActive(){if(active?.keep)setKeep(activeSegment,false)}
 function restoreActive(){if(active&&!active.keep)setKeep(activeSegment,true)}

 async function smartCut(){
  const source=videoRef.current;if(!source||!duration||detecting)return;setDetecting(true);setError('');const old=source.currentTime,wasPlaying=!source.paused;source.pause()
  try{
   const canvas=document.createElement('canvas');canvas.width=96;canvas.height=54;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Seu navegador não conseguiu iniciar a análise de cenas.')
   const step=Math.max(2,Math.min(8,duration/70)),marks:number[]=[];let previous:Uint8ClampedArray|null=null
   for(let t=0;t<duration;t+=step){source.currentTime=Math.min(duration-.05,t);await wait(source,'seeked').catch(()=>{});ctx.drawImage(source,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;if(previous){let diff=0;for(let i=0;i<data.length;i+=16)diff+=Math.abs(data[i]-previous[i])+Math.abs(data[i+1]-previous[i+1])+Math.abs(data[i+2]-previous[i+2]);const normalized=diff/(data.length/16*765);if(normalized>.19)marks.push(t)}previous=new Uint8ClampedArray(data)}
   const minGap=Math.max(8,Math.min(25,duration/14)),filtered=marks.filter((time,index)=>index===0||time-marks[index-1]>minGap),bounds=[0,...filtered,duration].sort((a,b)=>a-b);let detected:Segment[]=[]
   for(let i=0;i<bounds.length-1;i++)if(bounds[i+1]-bounds[i]>.7)detected.push({id:uid(),start:bounds[i],end:bounds[i+1],keep:true})
   if(detected.length<2){const count=Math.min(5,Math.max(2,Math.ceil(duration/75))),size=duration/count;detected=Array.from({length:count},(_,i)=>({id:uid(),start:i*size,end:i===count-1?duration:(i+1)*size,keep:true}))}
   snapshot();setSegments(detected);setActiveSegment(0);seek(detected[0]?.start||0)
  }catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível analisar as cenas.')}finally{source.currentTime=old;if(wasPlaying)source.play().catch(()=>{});setDetecting(false)}
 }

 function addMusic(files:FileList|null){const picked=Array.from(files||[]).slice(0,Math.max(0,4-tracks.length));for(const f of picked){if(!f.type.startsWith('audio/')){setError('Escolha somente arquivos de áudio.');continue}if(f.size>25*1024*1024){setError('Cada música pode ter no máximo 25 MB.');continue}const url=URL.createObjectURL(f),audio=new Audio(url);audio.preload='metadata';audio.onloadedmetadata=()=>setTracks(items=>items.length>=4?items:[...items,{id:uid(),file:f,url,start:current,volume:.8,duration:Number.isFinite(audio.duration)?audio.duration:0}]);audio.onerror=()=>{URL.revokeObjectURL(url);setError(`Não foi possível abrir ${f.name}.`)}}}
 function updateTrack(id:string,patch:Partial<MusicTrack>){setTracks(items=>items.map(t=>t.id===id?{...t,...patch}:t))}
 function removeTrack(id:string){setTracks(items=>{const found=items.find(t=>t.id===id);if(found)URL.revokeObjectURL(found.url);return items.filter(t=>t.id!==id)})}

 async function generateCaptions(){
  if(captionStatus==='working'||!duration)return;setCaptionStatus('working');setCaptionMessage('Analisando a fala do vídeo no navegador…');setError('')
  const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setCaptionStatus('error');setCaptionMessage('Este navegador não oferece transcrição automática. Use Chrome ou Edge atualizado.');return}
  const probe=document.createElement('video');probe.src=sourceUrl;probe.preload='auto';probe.playsInline=true;probe.muted=true
  try{
   if(probe.readyState<1)await wait(probe,'loadedmetadata');const start=active?.start??0,end=active?.end??duration;probe.currentTime=start;await wait(probe,'seeked').catch(()=>{});await probe.play();const stream=(probe as any).captureStream?.()||(probe as any).mozCaptureStream?.(),audioTrack=stream?.getAudioTracks?.()[0];if(!audioTrack){probe.pause();throw new Error('O navegador não liberou o áudio do vídeo para transcrição.')}
   const recognition=new Speech();recognition.lang='pt-BR';recognition.continuous=true;recognition.interimResults=false;recognition.maxAlternatives=1;const generated:Caption[]=[];let lastTime=start
   recognition.onresult=(event:any)=>{for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i];if(!result.isFinal)continue;const text=String(result[0]?.transcript||'').trim();if(!text)continue;const finish=Math.min(end,Math.max(lastTime+1,probe.currentTime));generated.push({id:uid(),start:lastTime,end:finish,text});lastTime=finish;setCaptions([...generated])}}
   const done=new Promise<void>((resolve,reject)=>{recognition.onerror=(event:any)=>reject(new Error(event?.error==='not-allowed'?'O navegador bloqueou a transcrição de áudio.':`Falha na transcrição: ${event?.error||'erro desconhecido'}.`));recognition.onend=()=>resolve()})
   const timer=window.setInterval(()=>{if(probe.currentTime>=end-.1||probe.ended){probe.pause();try{recognition.stop()}catch{}}},180);try{recognition.start(audioTrack)}catch{throw new Error('Seu navegador não aceita transcrever diretamente o áudio do vídeo. Atualize o Chrome/Edge ou edite a legenda manualmente.')}await done;window.clearInterval(timer);probe.pause();audioTrack.stop?.();if(!generated.length)throw new Error('Não foi detectada fala nesse trecho. Você pode escrever a legenda manualmente.');setCaptions(generated);setCaptionStatus('ready');setCaptionMessage(`Português (Brasil) · ${generated.length} trecho${generated.length===1?'':'s'} gerado${generated.length===1?'':'s'}`)
  }catch(cause){probe.pause();setCaptionStatus('error');setCaptionMessage(cause instanceof Error?cause.message:'Não foi possível gerar as legendas.')}
 }
 const captionAt=(time:number)=>captions.find(c=>time>=c.start&&time<=c.end)

 function dimensions(video:HTMLVideoElement){if(ratio==='vertical')return quality==='720'?{width:720,height:1280}:{width:1080,height:1920};if(ratio==='square'){const side=quality==='720'?720:1080;return {width:side,height:side}};if(ratio==='wide')return quality==='720'?{width:1280,height:720}:{width:1920,height:1080};const max=quality==='720'?1280:quality==='1080'?1920:Math.max(video.videoWidth,video.videoHeight),scale=Math.min(1,max/Math.max(video.videoWidth,video.videoHeight));return {width:Math.max(2,Math.round(video.videoWidth*scale/2)*2),height:Math.max(2,Math.round(video.videoHeight*scale/2)*2)}}
 function drawFrame(ctx:CanvasRenderingContext2D,video:HTMLVideoElement,width:number,height:number,time:number,useOriginal:boolean){ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);const sr=video.videoWidth/video.videoHeight,tr=width/height;let sx=0,sy=0,sw=video.videoWidth,sh=video.videoHeight;if(!useOriginal&&ratio!=='original'){if(sr>tr){sw=video.videoHeight*tr;sx=(video.videoWidth-sw)/2}else{sh=video.videoWidth/tr;sy=(video.videoHeight-sh)/2}}ctx.drawImage(video,sx,sy,sw,sh,0,0,width,height);if(useOriginal)return;const text=captionAt(time)?.text||overlayText.trim();if(!text)return;const font=Math.max(24,Math.round(width*.035));ctx.font=`700 ${font}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';const maxWidth=width*.82,words=text.toUpperCase().split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);const lh=font*1.25,pad=font*.55,boxH=lines.length*lh+pad*2,y=height*.79;ctx.fillStyle='rgba(0,0,0,.76)';ctx.fillRect(width*.08,y-boxH/2,width*.84,boxH);lines.forEach((value,index)=>{ctx.fillStyle=index===lines.length-1&&lines.length>1?'#ff3047':'#fff';ctx.fillText(value,width/2,y-boxH/2+pad+lh*(index+.5),maxWidth)})}

 async function exportVideo(useOriginal=false){
  if(exporting||!duration)return;const kept=useOriginal?[{id:'original',start:0,end:duration,keep:true}]:segments.filter(s=>s.keep);if(!kept.length){setError('Mantenha pelo menos um clip na timeline.');return}const mime=recorderType();if(!mime){setError('Este navegador não possui exportação de vídeo compatível. Use Chrome ou Edge atualizado.');return}setExporting(true);setProgress(0);setError('');let context:AudioContext|null=null
  try{
   const render=document.createElement('video');render.src=sourceUrl;render.preload='auto';render.playsInline=true;if(render.readyState<1)await wait(render,'loadedmetadata');const canvas=document.createElement('canvas'),size=useOriginal?(()=>{const max=Math.max(render.videoWidth,render.videoHeight),scale=Math.min(1,1920/max);return {width:Math.max(2,Math.round(render.videoWidth*scale/2)*2),height:Math.max(2,Math.round(render.videoHeight*scale/2)*2)}})():dimensions(render);canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Não foi possível iniciar o renderizador.');const stream=canvas.captureStream(30);context=new AudioContext();const destination=context.createMediaStreamDestination(),mainSource=context.createMediaElementSource(render),mainGain=context.createGain();mainGain.gain.value=useOriginal?1:volume;mainSource.connect(mainGain).connect(destination)
   const audios=(useOriginal?[]:tracks).map(track=>{const audio=new Audio(track.url),source=context!.createMediaElementSource(audio),gain=context!.createGain();gain.gain.value=track.volume;source.connect(gain).connect(destination);return {track,audio,started:false}}),mixed=new MediaStream([...stream.getVideoTracks(),...destination.stream.getAudioTracks()]),recorder=new MediaRecorder(mixed,{mimeType:mime,videoBitsPerSecond:quality==='720'?3800000:6500000,audioBitsPerSecond:160000}),chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)}
   const complete=new Promise<File>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('O navegador interrompeu a exportação.'));recorder.onstop=()=>{const type=recorder.mimeType||mime,blob=new Blob(chunks,{type});if(!blob.size){reject(new Error('O vídeo exportado ficou vazio.'));return}const mp4=type.includes('mp4'),name=file.name.replace(/\.[^.]+$/,'');resolve(new File([blob],`${name}-fullsend.${mp4?'mp4':'webm'}`,{type:mp4?'video/mp4':'video/webm',lastModified:Date.now()}))}}),total=kept.reduce((sum,s)=>sum+s.end-s.start,0);let rendered=0;await context.resume();recorder.start(1000)
   for(const segment of kept){render.currentTime=segment.start;await wait(render,'seeked').catch(()=>{});render.playbackRate=useOriginal?1:speed;await render.play();await new Promise<void>((resolve,reject)=>{let raf=0;const paint=()=>{try{const sourceTime=render.currentTime;drawFrame(ctx,render,canvas.width,canvas.height,sourceTime,useOriginal);audios.forEach(item=>{const local=sourceTime-item.track.start;if(local>=0&&local<item.track.duration){item.audio.volume=item.track.volume;item.audio.playbackRate=useOriginal?1:speed;if(!item.started){item.started=true;item.audio.currentTime=Math.max(0,local);item.audio.play().catch(()=>{})}}else if(item.started){item.audio.pause();item.started=false}});setProgress(Math.min(99,(rendered+Math.max(0,Math.min(segment.end,sourceTime)-segment.start))/Math.max(.1,total)*100));if(sourceTime>=segment.end-.03||render.ended){render.pause();audios.forEach(item=>{item.audio.pause();item.started=false});resolve();return}raf=requestAnimationFrame(paint)}catch(cause){cancelAnimationFrame(raf);reject(cause)}};raf=requestAnimationFrame(paint);render.addEventListener('error',()=>{cancelAnimationFrame(raf);reject(new Error('O vídeo apresentou erro durante a exportação.'))},{once:true})});rendered+=segment.end-segment.start}
   recorder.stop();const output=await complete;setProgress(100);onConfirm(output)
  }catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível exportar o vídeo.')}finally{await context?.close().catch(()=>{});setExporting(false)}
 }

 const totalKept=segments.filter(s=>s.keep).reduce((sum,s)=>sum+s.end-s.start,0),currentCaption=captionAt(current),type=recorderType(),outputLabel=type.includes('mp4')?'MP4 · H.264':'WebM · compatível com o mural'
 const tools:[Tool,string,string,string][]=[['cut','✂','Cortar','Corte inteligente e divisão'],['music','♫','Música','Até 4 faixas de áudio'],['captions','CC','Legendas IA','Gerar e corrigir automaticamente'],['format','▣','Formato','9:16 · 1:1 · 16:9'],['speed','⚡','Velocidade','0.5x até 2x'],['text','T','Texto','Títulos e chamadas'],['cover','▧','Capa','Escolher frame de capa']]

 return <div className="fs-figma-backdrop" role="dialog" aria-modal="true" aria-label="FULLSEND Video Studio"><section className="fs-figma-studio">
  <header className="fs-figma-header"><div className="fs-desktop-brand"><strong>FULLSEND VIDEO STUDIO</strong><span>Editar vídeo · {file.name}</span></div><div className="fs-mobile-brand"><button type="button" onClick={onCancel} disabled={exporting}><ChevronLeft/></button><strong>STUDIO</strong></div><div className="fs-header-actions"><button type="button" className="fs-save-draft" disabled={exporting}><Save size={14}/><span>SALVAR RASCUNHO</span></button><button type="button" className="fs-export-top" onClick={()=>exportVideo(false)} disabled={exporting||!duration}>{exporting?'EXPORTANDO…':'GERAR VÍDEO'}</button><button type="button" className="fs-close" onClick={onCancel} disabled={exporting}><X/></button></div></header>

  <div className="fs-figma-workspace"><aside className="fs-tools-sidebar"><span className="fs-side-label">FERRAMENTAS</span>{tools.map(([value,icon,title,description])=><button type="button" key={value} className={tool===value?'active':''} onClick={()=>setTool(value)}><b>{icon}</b><span><strong>{title}</strong><small>{description}</small></span></button>)}<div className="fs-auto-cut-card"><strong>CORTE AUTOMÁTICO</strong><b>Clipes longos</b><span>Detecta mudanças de cena localmente, sem API e sem enviar o vídeo.</span><button type="button" onClick={smartCut} disabled={detecting||exporting}>{detecting?'ANALISANDO…':'ANALISAR CENAS'}</button></div></aside>

   <main className="fs-preview-workspace"><div className="fs-preview-badges"><span className="fs-long-badge">● VÍDEO {duration>180?'LONGO · ':''}{fmt(duration)}</span><span className={captionStatus==='ready'?'fs-caption-ready':'fs-caption-badge'}>{captionStatus==='ready'?'✓ LEGENDAS GERADAS':'CC LEGENDAS'}</span></div><div ref={stageRef} className={`fs-video-stage ratio-${ratio}`}><video ref={videoRef} src={sourceUrl} playsInline preload="metadata" onLoadedMetadata={e=>{const d=Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:0;setDuration(d);setSegments([{id:uid(),start:0,end:d,keep:true}]);setCoverTime(0);e.currentTarget.volume=volume}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={e=>{const time=e.currentTarget.currentTime;setCurrent(time);const seg=segments[activeSegment];if(seg&&time>=seg.end-.02){e.currentTarget.pause();e.currentTarget.currentTime=seg.start;setCurrent(seg.start)}}}/>{(currentCaption?.text||overlayText.trim())&&<div className="fs-caption-preview"><span>{currentCaption?.text||overlayText}</span></div>}</div><div className="fs-playback fs-desktop-player"><button type="button" title="Voltar 5 segundos" onClick={()=>jump(-5)}>−5</button><button type="button" className="main" title={playing?'Pausar':'Reproduzir'} onClick={toggle}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button type="button" title="Avançar 5 segundos" onClick={()=>jump(5)}>+5</button><span>{fmt(current)} / {fmt(duration)}</span><input type="range" min="0" max={duration||1} step=".01" value={Math.min(current,duration||0)} onChange={e=>seek(Number(e.target.value))}/><button type="button" title="Áudio" onClick={()=>setMuted(value=>!value)}>{muted?'🔇':'🔊'}</button><button type="button" title="Velocidade" onClick={cycleSpeed}>{speed}x</button><button type="button" title="Tela cheia" onClick={toggleFullscreen}>{fullscreen?'⤢':'⛶'}</button></div></main>

   <aside className="fs-properties"><span className="fs-side-label">PROPRIEDADES</span>
    {tool==='cut'&&<div className="fs-property-stack"><section><h3>CORTE ATUAL</h3><div className="fs-time-grid"><label>INÍCIO<input type="number" min="0" max={active?.end||duration} step=".1" value={active?.start??0} onChange={e=>patchActive({start:Math.min(Number(e.target.value),Math.max(0,(active?.end||duration)-.2))})}/></label><label>FIM<input type="number" min={active?.start||0} max={duration} step=".1" value={active?.end??duration} onChange={e=>patchActive({end:Math.max(Number(e.target.value),(active?.start||0)+.2)})}/></label></div><div className="fs-action-grid"><button type="button" onClick={()=>active&&patchActive({start:current})} disabled={!active||current>=active.end-.2}>INÍCIO AQUI</button><button type="button" onClick={()=>active&&patchActive({end:current})} disabled={!active||current<=active.start+.2}>FIM AQUI</button></div></section><section><h3>DIVISÃO</h3><button type="button" className="fs-wide-action" onClick={splitHere} disabled={!active}>✂ DIVIDIR NA AGULHA</button><button type="button" className="fs-wide-action" onClick={active?.keep?deleteActive:restoreActive} disabled={!active}>{active?.keep?'🗑 EXCLUIR CLIPE':'↩ RESTAURAR CLIPE'}</button><small>Excluir retira o clipe do vídeo final sem apagar o arquivo original. Você pode restaurar ou desfazer.</small></section></div>}
    {tool==='format'&&<div className="fs-property-stack"><section><h3>FORMATO</h3><div className="fs-format-grid">{([['vertical','9:16'],['square','1:1'],['wide','16:9'],['original','Original']] as [Ratio,string][]).map(([value,label])=><button type="button" key={value} className={ratio===value?'active':''} onClick={()=>setRatio(value)}>{label}</button>)}</div></section><section><h3>QUALIDADE</h3><div className="fs-quality-grid">{([['1080','1080p'],['720','720p'],['auto','Auto']] as [Quality,string][]).map(([value,label])=><button type="button" key={value} className={quality===value?'active':''} onClick={()=>setQuality(value)}>{label}</button>)}</div></section></div>}
    {tool==='speed'&&<div className="fs-property-stack"><section><h3>VELOCIDADE</h3><div className="fs-speed-grid">{([.5,1,1.5,2] as const).map(value=><button type="button" key={value} className={speed===value?'active':''} onClick={()=>setSpeed(value)}>{value}x</button>)}</div></section></div>}
    {tool==='music'&&<div className="fs-property-stack"><section><h3>♫ MÚSICAS</h3><p>{tracks.length} faixa{tracks.length===1?'':'s'} adicionada{tracks.length===1?'':'s'} · máximo 4</p><input ref={musicInput} hidden type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg" multiple onChange={e=>{addMusic(e.target.files);e.target.value=''}}/>{tracks.map(track=><div className="fs-music-row" key={track.id}><div><b>{track.file.name}</b><small>entra em {fmt(track.start)}</small></div><label><Volume2 size={12}/><input type="range" min="0" max="1" step=".05" value={track.volume} onChange={e=>updateTrack(track.id,{volume:Number(e.target.value)})}/></label><button type="button" onClick={()=>removeTrack(track.id)}><Trash2 size={13}/></button></div>)}<button type="button" className="fs-add-music" disabled={tracks.length>=4} onClick={()=>musicInput.current?.click()}>＋ ADICIONAR MÚSICA</button></section></div>}
    {tool==='captions'&&<div className="fs-property-stack"><section className="fs-caption-panel"><h3>CC LEGENDAS AUTOMÁTICAS</h3><p className={captionStatus==='error'?'error':captionStatus==='ready'?'ready':''}>{captionMessage}</p><button type="button" className="fs-wide-action" onClick={generateCaptions} disabled={captionStatus==='working'}>{captionStatus==='working'?'GERANDO…':captionStatus==='ready'?'REGERAR LEGENDAS':'GERAR LEGENDAS'}</button>{captions.map((caption,index)=><label className="fs-caption-edit" key={caption.id}><span>{fmt(caption.start)}–{fmt(caption.end)}</span><textarea rows={2} value={caption.text} onChange={e=>setCaptions(items=>items.map((c,i)=>i===index?{...c,text:e.target.value}:c))}/></label>)}</section></div>}
    {tool==='text'&&<div className="fs-property-stack"><section><h3>TEXTO</h3><textarea rows={4} value={overlayText} maxLength={120} placeholder="Título ou chamada no vídeo…" onChange={e=>setOverlayText(e.target.value)}/><small>O texto aparece na área inferior e é gravado no vídeo exportado.</small></section></div>}
    {tool==='cover'&&<div className="fs-property-stack"><section><h3>CAPA</h3><p>Frame escolhido: {fmt(coverTime)}</p><button type="button" className="fs-wide-action" onClick={()=>setCoverTime(current)}><ImageIcon size={14}/> USAR FRAME ATUAL</button><small>A capa fica salva nesta edição enquanto o editor está aberto.</small></section></div>}
    <section className="fs-original-audio"><h3>ÁUDIO ORIGINAL</h3><div><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><b>{Math.round(volume*100)}%</b></div></section><section className="fs-output-card"><h3>SAÍDA</h3><b>{outputLabel}</b><span>{ratio==='vertical'?'1080 × 1920':ratio==='square'?'1080 × 1080':ratio==='wide'?'1920 × 1080':'Resolução original'} · {quality==='720'?'720p':quality==='auto'?'Auto':'1080p'}</span><button type="button" onClick={()=>exportVideo(false)} disabled={exporting||!duration}>GERAR VÍDEO</button></section>
   </aside></div>

  <section className="fs-mobile-player" aria-label="Player do vídeo">
   <div className="fs-mobile-player-main">
    <button type="button" aria-label="Voltar 5 segundos" onClick={()=>jump(-5)}>↶5</button>
    <button type="button" className="play" aria-label={playing?'Pausar':'Reproduzir'} onClick={toggle}>{playing?<Pause size={22}/>:<Play size={22}/>}</button>
    <button type="button" aria-label="Avançar 5 segundos" onClick={()=>jump(5)}>5↷</button>
    <span>{fmt(current)} / {fmt(duration)}</span>
    <button type="button" aria-label={muted?'Ativar áudio':'Silenciar'} onClick={()=>setMuted(value=>!value)}>{muted?'🔇':'🔊'}</button>
    <button type="button" aria-label="Tela cheia" onClick={toggleFullscreen}>{fullscreen?'⤢':'⛶'}</button>
   </div>
   <input className="fs-mobile-player-seek" aria-label="Posição do vídeo" type="range" min="0" max={duration||1} step=".01" value={Math.min(current,duration||0)} onChange={e=>seek(Number(e.target.value))}/>
   <div className="fs-mobile-player-fine">
    <button type="button" onClick={()=>stepFrame(-1)}>◀ FRAME</button>
    <button type="button" onClick={()=>stepFrame(1)}>FRAME ▶</button>
    <button type="button" onClick={cycleSpeed}>{speed}x</button>
   </div>
  </section>
  <section className="fs-mobile-quick">{([['cut','✂','CORTAR'],['music','♫','MÚSICA'],['captions','CC','LEGENDAS'],['format','▣','FORMATO'],['speed','⚡','VELOC.']] as [Tool,string,string][]).map(([value,icon,label])=><button type="button" key={value} className={tool===value?'active':''} onClick={()=>setTool(value)}><b>{icon}</b><span>{label}</span></button>)}</section>
  <section className="fs-mobile-tool-panel">
   {tool==='cut'&&<div className="fs-mobile-panel-card"><strong>✂ CORTE</strong><div className="fs-mobile-panel-actions"><button type="button" onClick={splitHere} disabled={!active}>✂ DIVIDIR</button><button type="button" className="danger" onClick={active?.keep?deleteActive:restoreActive} disabled={!active}>{active?.keep?'🗑 EXCLUIR':'↩ RESTAURAR'}</button><button type="button" onClick={undo} disabled={!undoStack.length}>↶ DESFAZER</button></div><small>Toque no clipe da timeline para selecionar. A agulha define onde dividir.</small></div>}
   {tool==='music'&&<div className="fs-mobile-panel-card"><strong>♫ MÚSICA</strong><button type="button" className="fs-mobile-primary" disabled={tracks.length>=4} onClick={()=>musicInput.current?.click()}>+ ADICIONAR MÚSICA</button>{tracks.map(track=><div className="fs-mobile-music-row" key={track.id}><div><b>{track.file.name}</b><small>entra em {fmt(track.start)}</small></div><input aria-label={"Volume "+track.file.name} type="range" min="0" max="1" step=".05" value={track.volume} onChange={e=>updateTrack(track.id,{volume:Number(e.target.value)})}/><button type="button" aria-label="Excluir música" onClick={()=>removeTrack(track.id)}><Trash2 size={15}/></button></div>)}{!tracks.length&&<small>Nenhuma música adicionada. Toque no botão acima para escolher do celular.</small>}</div>}
   {tool==='captions'&&<div className="fs-mobile-panel-card"><strong>CC LEGENDAS</strong><button type="button" className="fs-mobile-primary" onClick={generateCaptions} disabled={captionStatus==='working'}>{captionStatus==='working'?'GERANDO…':captionStatus==='ready'?'REGERAR LEGENDAS':'GERAR LEGENDAS'}</button><small className={captionStatus==='error'?'error':captionStatus==='ready'?'ready':''}>{captionMessage}</small>{captions.map((caption,index)=><label className="fs-mobile-caption-edit" key={caption.id}><span>{fmt(caption.start)}–{fmt(caption.end)}</span><textarea rows={2} value={caption.text} onChange={e=>setCaptions(items=>items.map((c,i)=>i===index?{...c,text:e.target.value}:c))}/></label>)}</div>}
   {tool==='format'&&<div className="fs-mobile-panel-card"><strong>▣ FORMATO</strong><div className="fs-mobile-choice-grid">{([['vertical','9:16'],['square','1:1'],['wide','16:9'],['original','ORIGINAL']] as [Ratio,string][]).map(([value,label])=><button type="button" key={value} className={ratio===value?'active':''} onClick={()=>setRatio(value)}>{label}</button>)}</div><strong className="sub">QUALIDADE</strong><div className="fs-mobile-choice-grid three">{([['1080','1080p'],['720','720p'],['auto','AUTO']] as [Quality,string][]).map(([value,label])=><button type="button" key={value} className={quality===value?'active':''} onClick={()=>setQuality(value)}>{label}</button>)}</div></div>}
   {tool==='speed'&&<div className="fs-mobile-panel-card"><strong>⚡ VELOCIDADE</strong><div className="fs-mobile-choice-grid">{([.5,1,1.5,2] as const).map(value=><button type="button" key={value} className={speed===value?'active':''} onClick={()=>setSpeed(value)}>{value}x</button>)}</div><small>Velocidade atual: {speed}x</small></div>}
  </section>
  <section className="fs-mobile-status"><button type="button" className={captionStatus==='ready'?'ready':''} onClick={()=>setTool('captions')}><b>{captionStatus==='ready'?'✓ Legendas automáticas prontas':'CC Legendas automáticas'}</b><small>{captionStatus==='ready'?'Português BR · toque para revisar':captionMessage}</small></button><button type="button" onClick={()=>setTool('music')}><b>♫ {tracks.length} música{tracks.length===1?'':'s'} adicionada{tracks.length===1?'':'s'}</b><span>+ MÚSICA</span></button></section>

  <section className="fs-timeline"><header><div><strong>TIMELINE</strong><button type="button" onClick={smartCut} disabled={detecting}><Sparkles size={13}/>{detecting?'ANALISANDO':'CORTE IA'}</button><button type="button" onClick={splitHere}><Scissors size={13}/>DIVIDIR</button><button type="button" onClick={active?.keep?deleteActive:restoreActive} disabled={!active}>{active?.keep?<><Trash2 size={13}/>EXCLUIR</>:<>↩ RESTAURAR</>}</button><button type="button" onClick={undo} disabled={!undoStack.length}><RotateCcw size={14}/></button></div><span>{fmt(totalKept)}</span></header><div className="fs-timeline-scroll"><div className="fs-ruler">{Array.from({length:7},(_,i)=><span key={i}>{fmt(duration*i/6)}</span>)}</div><div className="fs-lane"><b>VÍDEO</b><div className="fs-lane-track">{segments.map((segment,index)=><button type="button" key={segment.id} className={`fs-video-clip ${index===activeSegment?'selected':''} ${segment.keep?'':'removed'}`} style={{left:`${duration?segment.start/duration*100:0}%`,width:`${duration?(segment.end-segment.start)/duration*100:0}%`}} onClick={()=>selectSegment(index)} onDoubleClick={()=>toggleKeep(index)}><span>CLIP {String(index+1).padStart(2,'0')} · {fmt(segment.start)}–{fmt(segment.end)}</span></button>)}<i className="fs-playhead" style={{left:`${duration?current/duration*100:0}%`}}/></div></div>{tracks.slice(0,2).map((track,index)=><div className="fs-lane" key={track.id}><b>ÁUDIO {index+1}</b><div className="fs-lane-track"><div className="fs-audio-clip" style={{left:`${duration?track.start/duration*100:0}%`,width:`${duration?Math.min(track.duration,Math.max(0,duration-track.start))/duration*100:0}%`}}>♫ {track.file.name}</div></div></div>)}<div className="fs-lane"><b>CC LEGENDAS</b><div className="fs-lane-track">{captions.map(c=><div className="fs-caption-clip" key={c.id} style={{left:`${duration?c.start/duration*100:0}%`,width:`${duration?(c.end-c.start)/duration*100:0}%`}}>{c.text}</div>)}</div></div></div><small>Clipes divididos sem perder o original · EXCLUIR retira o clipe do vídeo final · duplo clique também remove/recoloca</small></section>

  {error&&<div className="fs-studio-error" role="alert">{error}</div>}{exporting&&<div className="fs-export-progress" role="status"><div style={{width:`${progress}%`}}/><span>GERANDO VÍDEO · {Math.round(progress)}%</span></div>}
  <footer className="fs-mobile-bottom"><button type="button" onClick={()=>exportVideo(true)} disabled={exporting||!duration}>SEM EDIÇÃO</button><button type="button" onClick={()=>exportVideo(false)} disabled={exporting||!duration}><Check size={14}/>{exporting?'GERANDO…':'GERAR VÍDEO'}</button></footer>
 </section></div>
}
