create extension if not exists pgcrypto;
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '', city text, state text, whatsapp text,
  avatar_url text, bio text, instagram text, role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade,
  category_slug text not null, title text not null, slug text unique not null, description text,
  price numeric(14,2), city text, state text, whatsapp text, cover_url text, media jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}', status text not null default 'active' check (status in ('draft','pending','active','sold','blocked')),
  source text not null default 'fullsend' check (source in ('fullsend','gecko')), external_id text, external_url text,
  source_payload jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists listings_source_external_uidx on public.listings(source,external_id) where external_id is not null;
create index if not exists listings_search_idx on public.listings using gin (to_tsvector('portuguese', coalesce(title,'')||' '||coalesce(description,'')));
create table if not exists public.favorites (user_id uuid references auth.users(id) on delete cascade, listing_id uuid references public.listings(id) on delete cascade, created_at timestamptz default now(), primary key(user_id,listing_id));
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid references auth.users(id) on delete set null, listing_id uuid references public.listings(id) on delete cascade, reason text not null, created_at timestamptz default now());
create table if not exists public.audit_logs (id bigint generated by default as identity primary key, actor_id uuid, action text not null, entity text, entity_id text, data jsonb, created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,name,city,state,whatsapp) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),new.raw_user_meta_data->>'city',upper(new.raw_user_meta_data->>'state'),new.raw_user_meta_data->>'whatsapp') on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;alter table public.listings enable row level security;alter table public.favorites enable row level security;alter table public.reports enable row level security;alter table public.audit_logs enable row level security;
create policy "profiles_public_read" on public.profiles for select using (true);
create policy "profiles_self_update" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create policy "listings_public_read" on public.listings for select using (status='active' or auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "listings_owner_insert" on public.listings for insert with check (auth.uid()=user_id and source='fullsend');
create policy "listings_owner_update" on public.listings for update using (auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "listings_owner_delete" on public.listings for delete using (auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "favorites_own_all" on public.favorites for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "reports_insert_authenticated" on public.reports for insert with check (auth.uid()=reporter_id);
create policy "reports_admin_read" on public.reports for select using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "audit_admin_read" on public.audit_logs for select using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('listing-media','listing-media',true,20971520,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm']) on conflict(id) do nothing;
create policy "media_public_read" on storage.objects for select using(bucket_id='listing-media');
create policy "media_owner_insert" on storage.objects for insert to authenticated with check(bucket_id='listing-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "media_owner_delete" on storage.objects for delete to authenticated using(bucket_id='listing-media' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace view public.listings_public as select id,user_id,category_slug,title,slug,description,price,city,state,whatsapp,cover_url,media,tags,status,source,external_url,created_at from public.listings where status='active';
grant select on public.listings_public to anon,authenticated;
