-- FULLSEND - BUSCAS AUTOMÁTICAS DE ANÚNCIOS
-- Painel administrativo: carro/termo + cidade + estado + liga/desliga + execução diária.

create extension if not exists pgcrypto;

create table if not exists public.import_search_jobs (
  id uuid primary key default gen_random_uuid(),
  name text,
  keyword text not null,
  city text,
  state text,
  pages smallint not null default 1 check (pages between 1 and 5),
  enabled boolean not null default false,
  frequency text not null default 'daily' check (frequency in ('daily')),
  run_ai_after_import boolean not null default false,

  last_run_at timestamptz,
  last_status text,
  last_received integer not null default 0,
  last_imported integer not null default 0,
  last_error text,

  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.import_search_logs (
  id bigint generated by default as identity primary key,
  job_id uuid references public.import_search_jobs(id) on delete cascade,
  keyword text,
  city text,
  state text,
  trigger_source text not null default 'manual',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  received integer not null default 0,
  imported integer not null default 0,
  pages_processed integer not null default 0,
  error text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists import_search_jobs_enabled_idx
  on public.import_search_jobs(enabled, updated_at desc);

create index if not exists import_search_logs_job_idx
  on public.import_search_logs(job_id, started_at desc);

alter table public.import_search_jobs enable row level security;
alter table public.import_search_logs enable row level security;

-- O painel usa Service Role no servidor. Nenhuma policy pública é criada.
grant all privileges on table public.import_search_jobs to service_role;
grant all privileges on table public.import_search_logs to service_role;
grant usage, select on sequence public.import_search_logs_id_seq to service_role;

comment on table public.import_search_jobs is
  'Buscas configuradas pelo administrador para importação manual/diária de anúncios.';
