-- FULLSEND - ANALYTICS PRÓPRIO
-- Visitantes, sessões, pageviews e tempo ativo.
-- Não armazena IP nem fingerprint.

create extension if not exists pgcrypto;

create table if not exists public.analytics_sessions (
  session_key uuid primary key,
  visitor_key uuid not null,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  pageviews integer not null default 1 check (pageviews >= 1),
  entry_path text not null default '/',
  last_path text not null default '/',
  referrer_host text,
  device_type text not null default 'desktop'
    check (device_type in ('desktop','mobile','tablet','unknown')),
  browser_family text not null default 'other',
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_pageviews (
  id bigint generated by default as identity primary key,
  session_key uuid not null references public.analytics_sessions(session_key) on delete cascade,
  visitor_key uuid not null,
  path text not null,
  viewed_at timestamptz not null default now()
);

create index if not exists analytics_sessions_started_idx
  on public.analytics_sessions(started_at desc);

create index if not exists analytics_sessions_last_seen_idx
  on public.analytics_sessions(last_seen_at desc);

create index if not exists analytics_sessions_visitor_idx
  on public.analytics_sessions(visitor_key, started_at desc);

create index if not exists analytics_pageviews_viewed_idx
  on public.analytics_pageviews(viewed_at desc);

create index if not exists analytics_pageviews_path_idx
  on public.analytics_pageviews(path, viewed_at desc);

alter table public.analytics_sessions enable row level security;
alter table public.analytics_pageviews enable row level security;

-- O navegador NÃO escreve diretamente no banco.
-- /api/analytics/track valida os dados e usa Service Role no servidor.
revoke all on table public.analytics_sessions from anon, authenticated;
revoke all on table public.analytics_pageviews from anon, authenticated;
grant all privileges on table public.analytics_sessions to service_role;
grant all privileges on table public.analytics_pageviews to service_role;
grant usage, select on sequence public.analytics_pageviews_id_seq to service_role;

create or replace function public.analytics_touch_session(
  p_session_key uuid,
  p_visitor_key uuid,
  p_action text,
  p_path text,
  p_duration integer,
  p_referrer_host text,
  p_device_type text,
  p_browser_family text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_path text := left(coalesce(nullif(p_path,''),'/'), 300);
  v_duration integer := greatest(0, least(coalesce(p_duration,0), 43200));
  v_device text := case when p_device_type in ('desktop','mobile','tablet','unknown') then p_device_type else 'unknown' end;
begin
  if p_action = 'pageview' then
    insert into public.analytics_sessions(
      session_key, visitor_key, started_at, last_seen_at, duration_seconds,
      pageviews, entry_path, last_path, referrer_host, device_type, browser_family
    )
    values(
      p_session_key, p_visitor_key, now(), now(), v_duration,
      1, v_path, v_path, nullif(left(coalesce(p_referrer_host,''),180),''),
      v_device, left(coalesce(nullif(p_browser_family,''),'other'),40)
    )
    on conflict(session_key) do update set
      last_seen_at = now(),
      duration_seconds = greatest(public.analytics_sessions.duration_seconds, excluded.duration_seconds),
      pageviews = public.analytics_sessions.pageviews + 1,
      last_path = excluded.last_path;

    insert into public.analytics_pageviews(session_key, visitor_key, path, viewed_at)
    values(p_session_key, p_visitor_key, v_path, now());

  elsif p_action in ('heartbeat','end') then
    update public.analytics_sessions set
      last_seen_at = now(),
      duration_seconds = greatest(duration_seconds, v_duration),
      last_path = v_path
    where session_key = p_session_key
      and visitor_key = p_visitor_key;
  end if;
end;
$$;

revoke all on function public.analytics_touch_session(uuid,uuid,text,text,integer,text,text,text)
  from public, anon, authenticated;
grant execute on function public.analytics_touch_session(uuid,uuid,text,text,integer,text,text,text)
  to service_role;

comment on table public.analytics_sessions is
  'Analytics próprio FULLSEND. Sessões anônimas; não armazena endereço IP ou fingerprint.';
comment on table public.analytics_pageviews is
  'Visualizações de páginas anônimas do FULLSEND.';
