-- FULLSEND V17 — Sistema profissional de reputação e XP
-- ROOKIE → STREET → GEARHEAD → BUILDER → PRO BUILDER → ELITE → LEGEND

alter table public.profiles
  add column if not exists xp_points integer not null default 0,
  add column if not exists reputation_level text not null default 'ROOKIE';

do $$ begin
  alter table public.profiles add constraint profiles_xp_nonnegative check (xp_points >= 0);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles add constraint profiles_reputation_level_check
    check (reputation_level in ('ROOKIE','STREET','GEARHEAD','BUILDER','PRO BUILDER','ELITE','LEGEND'));
exception when duplicate_object then null; end $$;


-- Usuários comuns podem editar somente dados de perfil. XP, nível, função e selo
-- ficam protegidos no banco e só podem ser alterados pelo backend/service role.
revoke update on public.profiles from authenticated;
grant update(name,city,state,whatsapp,avatar_url,bio,instagram,updated_at) on public.profiles to authenticated;

create index if not exists profiles_xp_points_idx on public.profiles(xp_points desc);
create index if not exists profiles_reputation_level_idx on public.profiles(reputation_level);

create table if not exists public.xp_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_key text not null,
  points integer not null,
  source_type text not null default 'system',
  source_id text not null default 'general',
  note text,
  created_at timestamptz not null default now(),
  unique(user_id,action_key,source_type,source_id)
);

create index if not exists xp_ledger_user_created_idx on public.xp_ledger(user_id,created_at desc);
create index if not exists xp_ledger_action_date_idx on public.xp_ledger(action_key,created_at desc);

alter table public.xp_ledger enable row level security;
drop policy if exists "xp_ledger_self_read" on public.xp_ledger;
create policy "xp_ledger_self_read" on public.xp_ledger for select to authenticated using(user_id=auth.uid());
drop policy if exists "xp_ledger_admin_read" on public.xp_ledger;
create policy "xp_ledger_admin_read" on public.xp_ledger for select to authenticated using(
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
);
grant select on public.xp_ledger to authenticated;
grant all privileges on public.xp_ledger to service_role;
grant usage,select on sequence public.xp_ledger_id_seq to service_role;

create or replace function public.fullsend_level_for_xp(p_xp integer)
returns text language sql immutable as $$
  select case
    when greatest(coalesce(p_xp,0),0) >= 12000 then 'LEGEND'
    when greatest(coalesce(p_xp,0),0) >= 6000 then 'ELITE'
    when greatest(coalesce(p_xp,0),0) >= 3000 then 'PRO BUILDER'
    when greatest(coalesce(p_xp,0),0) >= 1500 then 'BUILDER'
    when greatest(coalesce(p_xp,0),0) >= 750 then 'GEARHEAD'
    when greatest(coalesce(p_xp,0),0) >= 250 then 'STREET'
    else 'ROOKIE'
  end;
$$;

create or replace function public.award_xp(
  p_user uuid,
  p_action text,
  p_points integer,
  p_source_type text default 'system',
  p_source_id text default 'general',
  p_daily_cap integer default null,
  p_note text default null
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  v_today integer:=0;
  v_award integer:=greatest(coalesce(p_points,0),0);
  v_inserted bigint;
begin
  if p_user is null or v_award<=0 then return 0; end if;
  if not exists(select 1 from public.profiles where id=p_user) then return 0; end if;

  if exists(
    select 1 from public.xp_ledger
    where user_id=p_user and action_key=p_action and source_type=coalesce(nullif(p_source_type,''),'system') and source_id=coalesce(nullif(p_source_id,''),'general')
  ) then return 0; end if;

  if p_daily_cap is not null then
    select coalesce(sum(greatest(points,0)),0)::integer into v_today
    from public.xp_ledger
    where user_id=p_user and action_key=p_action and created_at>=date_trunc('day',now());
    v_award:=least(v_award,greatest(p_daily_cap-v_today,0));
    if v_award<=0 then return 0; end if;
  end if;

  insert into public.xp_ledger(user_id,action_key,points,source_type,source_id,note)
  values(p_user,p_action,v_award,coalesce(nullif(p_source_type,''),'system'),coalesce(nullif(p_source_id,''),'general'),p_note)
  on conflict(user_id,action_key,source_type,source_id) do nothing
  returning id into v_inserted;

  if v_inserted is null then return 0; end if;

  update public.profiles
  set xp_points=greatest(coalesce(xp_points,0)+v_award,0),
      reputation_level=public.fullsend_level_for_xp(greatest(coalesce(xp_points,0)+v_award,0)),
      updated_at=now()
  where id=p_user;

  return v_award;
end;
$$;

revoke all on function public.award_xp(uuid,text,integer,text,text,integer,text) from public,anon,authenticated;
grant execute on function public.award_xp(uuid,text,integer,text,text,integer,text) to service_role;

-- Publicação de anúncio FULLSEND: +40, apenas uma vez por anúncio.
create or replace function public.xp_on_listing_active() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.source='fullsend' and new.status='active' and new.user_id is not null then
    if tg_op='INSERT' then
      perform public.award_xp(new.user_id,'listing_published',40,'listing',new.id::text,null,'Anúncio publicado no FULLSEND');
    elsif tg_op='UPDATE' and old.status is distinct from new.status then
      perform public.award_xp(new.user_id,'listing_published',40,'listing',new.id::text,null,'Anúncio publicado no FULLSEND');
    end if;
  end if;
  return new;
end;$$;
drop trigger if exists trg_xp_listing_active on public.listings;
create trigger trg_xp_listing_active after insert or update of status on public.listings
for each row execute function public.xp_on_listing_active();

-- Evento criado por usuário e aprovado: +50 uma vez.
create or replace function public.xp_on_event_published() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.source='fullsend' and new.status='published' and new.created_by is not null then
    if tg_op='INSERT' then
      perform public.award_xp(new.created_by,'event_published',50,'event',new.id::text,null,'Evento aprovado no FULLSEND');
    elsif tg_op='UPDATE' and old.status is distinct from new.status then
      perform public.award_xp(new.created_by,'event_published',50,'event',new.id::text,null,'Evento aprovado no FULLSEND');
    end if;
  end if;
  return new;
end;$$;
drop trigger if exists trg_xp_event_published on public.events;
create trigger trg_xp_event_published after insert or update of status on public.events
for each row execute function public.xp_on_event_published();

-- Confirmar presença: +5, limite 25 XP/dia.
create or replace function public.xp_on_event_attendance() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  perform public.award_xp(new.user_id,'event_attendance',5,'event_attendance',new.event_id::text||':'||new.user_id::text,25,'Presença confirmada em evento');
  return new;
end;$$;
drop trigger if exists trg_xp_event_attendance on public.event_attendees;
create trigger trg_xp_event_attendance after insert on public.event_attendees
for each row execute function public.xp_on_event_attendance();

-- Mensagem enviada: +2, limite 20 XP/dia.
create or replace function public.xp_on_message_sent() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.sender_id is not null then
    perform public.award_xp(new.sender_id,'message_sent',2,'message',new.id::text,20,'Participação em conversa FULLSEND');
  end if;
  return new;
end;$$;
drop trigger if exists trg_xp_message_sent on public.messages;
create trigger trg_xp_message_sent after insert on public.messages
for each row execute function public.xp_on_message_sent();

-- Favorito recebido no anúncio: +3 para o anunciante, limite 30 XP/dia.
create or replace function public.xp_on_favorite_received() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_owner uuid;
begin
  select user_id into v_owner from public.listings where id=new.listing_id and status='active';
  if v_owner is not null and v_owner<>new.user_id then
    perform public.award_xp(v_owner,'favorite_received',3,'favorite',new.listing_id::text||':'||new.user_id::text,30,'Favorito recebido em anúncio');
  end if;
  return new;
end;$$;
drop trigger if exists trg_xp_favorite_received on public.favorites;
create trigger trg_xp_favorite_received after insert on public.favorites
for each row execute function public.xp_on_favorite_received();

-- Garante consistência para perfis existentes.
update public.profiles
set xp_points=greatest(coalesce(xp_points,0),0),
    reputation_level=public.fullsend_level_for_xp(greatest(coalesce(xp_points,0),0));

create or replace function public.search_public_listings(
  p_page integer default 1,
  p_page_size integer default 16,
  p_query text default null,
  p_state text default null,
  p_city text default null,
  p_category text default null,
  p_brand text default null,
  p_model text default null,
  p_price_min numeric default null,
  p_price_max numeric default null,
  p_year_min integer default null,
  p_year_max integer default null,
  p_km_min integer default null,
  p_km_max integer default null,
  p_fuel text default null,
  p_transmission text default null,
  p_style text default null,
  p_sort text default 'recent'
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with params as (
  select
    greatest(coalesce(p_page, 1), 1) as page_no,
    least(greatest(coalesce(p_page_size, 16), 1), 50) as page_size,
    nullif(btrim(p_query), '') as q,
    nullif(upper(btrim(p_state)), '') as state_q,
    nullif(btrim(p_city), '') as city_q,
    nullif(btrim(p_category), '') as category_q,
    nullif(btrim(p_brand), '') as brand_q,
    nullif(btrim(p_model), '') as model_q,
    nullif(btrim(p_fuel), '') as fuel_q,
    nullif(btrim(p_transmission), '') as transmission_q,
    nullif(lower(btrim(p_style)), '') as style_q,
    coalesce(nullif(btrim(p_sort), ''), 'recent') as sort_q
),
unified as (
  select
    l.id::text as id,
    'fullsend'::text as kind,
    l.title,
    l.price,
    l.city,
    l.state,
    l.cover_url,
    l.slug,
    null::text as external_url,
    l.brand,
    l.model,
    l.year,
    l.mileage,
    l.fuel,
    l.transmission,
    l.category_slug,
    coalesce(l.vehicle_styles,'{}'::text[]) as vehicle_styles,
    l.features,
    coalesce(l.is_featured,false) as is_featured,
    coalesce(l.is_vip,false) as is_vip,
    l.created_at as sort_date,
    concat_ws(' ',l.title,l.description,l.features,l.brand,l.model,l.city,l.state,array_to_string(l.tags,' '),array_to_string(l.vehicle_styles,' '),l.category_slug,l.engine,l.color,l.body_type) as search_text,
    jsonb_build_object('id',pr.id,'name',pr.name,'avatar_url',pr.avatar_url,'badge',pr.badge,'xp_points',coalesce(pr.xp_points,0),'reputation_level',coalesce(pr.reputation_level,'ROOKIE')) as seller
  from public.listings l
  left join public.profiles pr on pr.id=l.user_id
  where l.status='active'

  union all

  select
    g.id::text,
    'gecko'::text,
    g.title,
    g.price,
    g.city,
    g.state,
    g.image_url,
    null::text,
    g.external_url,
    g.brand,
    g.model,
    g.year,
    g.mileage,
    g.fuel,
    g.transmission,
    case
      when lower(coalesce(g.import_search_category,''))='vehicles' then 'carros'
      when lower(coalesce(g.import_search_category,'')) in ('engine_parts','performance') then 'motores'
      when lower(coalesce(g.import_search_category,''))='wheels_tires' then 'rodas'
      when lower(coalesce(g.import_search_category,''))='suspension' then 'suspensao'
      when lower(coalesce(g.import_search_category,''))='audio' then 'som'
      when lower(coalesce(g.import_search_category,''))='accessories' then 'acessorios'
      when lower(coalesce(g.category,'')) ~ '(motor|turbo|turbina|injec)' then 'motores'
      when lower(coalesce(g.category,'')) ~ '(roda|pneu)' then 'rodas'
      when lower(coalesce(g.category,'')) ~ 'suspens' then 'suspensao'
      when lower(coalesce(g.category,'')) ~ '(som|audio)' then 'som'
      when lower(coalesce(g.category,'')) ~ '(acessor|peca)' then 'acessorios'
      else 'carros'
    end,
    '{}'::text[],
    g.features,
    coalesce(g.is_featured,false),
    coalesce(g.is_vip,false),
    coalesce(g.listed_at,g.imported_at),
    concat_ws(' ',g.title,g.brand,g.model,g.features,g.city,g.state,g.category,g.raw_data::text),
    null::jsonb
  from public.gecko_listings g
  where g.status='active'
),
filtered as (
  select u.*
  from unified u
  cross join params p
  where
    not (coalesce(u.is_vip,false) or coalesce(u.is_featured,false))
    and (p.q is null or u.search_text ilike '%'||p.q||'%')
    and (p.state_q is null or upper(coalesce(u.state,''))=p.state_q)
    and (p.city_q is null or coalesce(u.city,'') ilike '%'||p.city_q||'%')
    and (p.category_q is null or u.category_slug=p.category_q)
    and (p.brand_q is null or coalesce(u.brand,'') ilike '%'||p.brand_q||'%')
    and (p.model_q is null or coalesce(u.model,'') ilike '%'||p.model_q||'%')
    and (p_price_min is null or u.price>=p_price_min)
    and (p_price_max is null or u.price<=p_price_max)
    and (p_year_min is null or u.year>=p_year_min)
    and (p_year_max is null or u.year<=p_year_max)
    and (p_km_min is null or u.mileage>=p_km_min)
    and (p_km_max is null or u.mileage<=p_km_max)
    and (p.fuel_q is null or coalesce(u.fuel,'') ilike '%'||p.fuel_q||'%')
    and (p.transmission_q is null or coalesce(u.transmission,'') ilike '%'||p.transmission_q||'%')
    and (
      p.style_q is null
      or (
        p.style_q='antigos'
        and (
          'antigo'=any(u.vehicle_styles)
          or (u.year is not null and u.year<2008)
        )
      )
      or (
        p.style_q='turbo'
        and (
          'turbo'=any(u.vehicle_styles)
          or lower(u.search_text) ~ '(^|[^a-z0-9])turbo([^a-z0-9]|$)|turbina|turbinad'
        )
      )
      or (
        p.style_q='rebaixado'
        and (
          'rebaixado'=any(u.vehicle_styles)
          or lower(u.search_text) ~ '(rebaixad|rebaixamento|carro baixo|baixinho|socado|stance|coilover|air ?ride|suspens[aã]o (a ar|de ar|rosca|fixa|regulavel|preparada))'
          or (
            u.kind='gecko'
            and exists (
              select 1 from public.gecko_listings gx
              where gx.id::text=u.id
                and (
                  gx.ai_manual_rebaixado=true
                  or (
                    gx.ai_manual_rebaixado is null
                    and gx.ai_rebaixado=true
                  )
                )
            )
          )
        )
      )
    )
),
ordered as (
  select f.*,
    row_number() over (
      order by
        case when (select sort_q from params)='price-asc' then f.price end asc nulls last,
        case when (select sort_q from params)='price-desc' then f.price end desc nulls last,
        case when (select sort_q from params)='year-desc' then f.year end desc nulls last,
        case when (select sort_q from params)='km-asc' then f.mileage end asc nulls last,
        case when (select sort_q from params) in ('recent','') then f.sort_date end desc nulls last,
        case when (select sort_q from params)='random' then md5(f.id) end asc,
        f.sort_date desc nulls last,
        f.id asc
    ) as rn
  from filtered f
),
paged as (
  select o.*
  from ordered o cross join params p
  where o.rn>((p.page_no-1)*p.page_size)
    and o.rn<=(p.page_no*p.page_size)
  order by o.rn
)
select jsonb_build_object(
  'total',(select count(*) from filtered),
  'page',(select page_no from params),
  'page_size',(select page_size from params),
  'items',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',pg.id,'kind',pg.kind,'title',pg.title,'price',pg.price,
      'city',pg.city,'state',pg.state,'cover_url',pg.cover_url,
      'slug',pg.slug,'external_url',pg.external_url,'brand',pg.brand,
      'model',pg.model,'year',pg.year,'mileage',pg.mileage,'fuel',pg.fuel,
      'transmission',pg.transmission,'category_slug',pg.category_slug,
      'features',pg.features,'is_featured',pg.is_featured,'is_vip',pg.is_vip,
      'created_at',pg.sort_date,'seller',pg.seller
    ) order by pg.rn) from paged pg
  ),'[]'::jsonb)
);
$$;

grant execute on function public.search_public_listings(
  integer,integer,text,text,text,text,text,text,
  numeric,numeric,integer,integer,integer,integer,
  text,text,text,text
) to anon,authenticated;
